main: com.github.zastrixarundell.mounts.Mounts
name: Mounts
version: ${version}
description: Plugin for mounts
authors: ["Zastrix"]
api-version: '1.15'

commands:
  mounts:
    usage: /<command>
    description: See all of your mounts.