main: com.github.zastrixarundell.mounts.Mounts
description: Plugin for ESO styled mounts.
version: ${version}
name: Mounts
author: Zastrix
api-version: '1.15'
depend:
  - Citizens

commands:
  mounts:
    description: Show available mounts
    usage: /<command>